default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: sammy
  password: password
  host: localhost
  database: adam_blogs

test:
  <<: *default
  username: sammy
  password: password
  host: localhost
  database: app_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: app_production
  username: app
  password: <%= ENV["APP_DATABASE_PASSWORD"] %>

